import type { SubscriptionApiType, SubscriptionModel } from "./subscriptions.js";

export interface ProviderPreset {
  id: string;
  name: string;
  providerId: string;
  apiType: SubscriptionApiType;
  baseUrl: string;
  models: SubscriptionModel[];
  notes?: string;
}

export const PROVIDER_PRESETS: readonly ProviderPreset[] = [
  {
    id: "openai-responses",
    name: "OpenAI (Responses)",
    providerId: "openai-responses",
    apiType: "openai-responses",
    baseUrl: "https://api.openai.com/v1",
    models: [{ id: "gpt-5.4", name: "GPT-5.4", contextWindow: 272000 }, { id: "gpt-5-mini", name: "GPT-5 mini", contextWindow: 128000 }, { id: "gpt-4o", name: "GPT-4o", contextWindow: 128000 }, { id: "gpt-4o-mini", name: "GPT-4o mini", contextWindow: 128000 }],
    notes: "OpenAI 官方 Responses API。",
  },
  {
    id: "openai-completions",
    name: "OpenAI (Completions)",
    providerId: "openai-completions",
    apiType: "openai-completions",
    baseUrl: "https://api.openai.com/v1",
    models: [{ id: "gpt-5.4", name: "GPT-5.4", contextWindow: 272000 }, { id: "gpt-4o", name: "GPT-4o", contextWindow: 128000 }],
    notes: "OpenAI 官方 Chat Completions API。",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    providerId: "anthropic",
    apiType: "anthropic-messages",
    baseUrl: "https://api.anthropic.com",
    models: [{ id: "claude-opus-4-7", name: "Claude Opus 4.7", contextWindow: 1000000 }, { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", contextWindow: 1000000 }, { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", contextWindow: 200000 }],
    notes: "Anthropic Messages API。",
  },
  {
    id: "google-gemini",
    name: "Google Gemini",
    providerId: "google-gemini",
    apiType: "google-generative-ai",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    models: [{ id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", contextWindow: 1048576 }, { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", contextWindow: 1048576 }],
    notes: "Google Generative Language API。",
  },
  {
    id: "groq",
    name: "Groq",
    providerId: "groq",
    apiType: "openai-completions",
    baseUrl: "https://api.groq.com/openai/v1",
    models: [{ id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B", contextWindow: 128000 }, { id: "qwen-2.5-32b", name: "Qwen 2.5 32B", contextWindow: 32768 }],
    notes: "Groq OpenAI 兼容接口。",
  },
  {
    id: "kimi",
    name: "Kimi",
    providerId: "kimi",
    apiType: "openai-responses",
    baseUrl: "https://api.moonshot.cn/v1",
    models: [{ id: "kimi-k2.7-code", name: "kimi-k2.7-code" }, { id: "kimi-k3", name: "Kimi K3", contextWindow: 1048576 }],
    notes: "来自 CC Switch（cn_official）· https://platform.kimi.com?aff=cc-switch",
  },
  {
    id: "kimi-for-coding",
    name: "Kimi For Coding",
    providerId: "kimi-for-coding",
    apiType: "openai-responses",
    baseUrl: "https://api.kimi.com/coding/v1",
    models: [{ id: "kimi-for-coding", name: "kimi-for-coding" }],
    notes: "来自 CC Switch（cn_official）· https://www.kimi.com/code/?aff=cc-switch",
  },
  {
    id: "packycode",
    name: "PackyCode",
    providerId: "packycode",
    apiType: "openai-responses",
    baseUrl: "https://www.packyapi.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://www.packyapi.ai",
  },
  {
    id: "zetaapi",
    name: "ZetaAPI",
    providerId: "zetaapi",
    apiType: "openai-responses",
    baseUrl: "https://api.zetaapi.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://zetaapi.ai",
  },
  {
    id: "apinebula",
    name: "APINebula",
    providerId: "apinebula",
    apiType: "openai-responses",
    baseUrl: "https://apinebula.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://apinebula.ai",
  },
  {
    id: "aicodemirror",
    name: "AICodeMirror",
    providerId: "aicodemirror",
    apiType: "openai-responses",
    baseUrl: "https://api.aicodemirror.ai/api/codex/backend-api/codex",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://www.aicodemirror.ai",
  },
  {
    id: "patewayai",
    name: "PatewayAI",
    providerId: "patewayai",
    apiType: "openai-responses",
    baseUrl: "https://api.pateway.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://pateway.ai",
  },
  {
    id: "fennoai",
    name: "FennoAI",
    providerId: "fennoai",
    apiType: "openai-responses",
    baseUrl: "https://api.fenno.ai",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://api.fenno.ai",
  },
  {
    id: "runapi",
    name: "RunAPI",
    providerId: "runapi",
    apiType: "openai-responses",
    baseUrl: "https://runapi.co/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://runapi.co",
  },
  {
    id: "shengsuanyun",
    name: "Shengsuanyun",
    providerId: "shengsuanyun",
    apiType: "openai-responses",
    baseUrl: "https://router.shengsuanyun.com/api/v1",
    models: [{ id: "openai/gpt-5.6-sol", name: "openai/gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://www.shengsuanyun.com/?from=CH_4HHXMRYF",
  },
  {
    id: "aigocode",
    name: "AIGoCode",
    providerId: "aigocode",
    apiType: "openai-responses",
    baseUrl: "https://api.aigocode.app",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://aigocode.app",
  },
  {
    id: "qiniu",
    name: "Qiniu",
    providerId: "qiniu",
    apiType: "openai-responses",
    baseUrl: "https://api.qnaigc.com/bypass/openai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://s.qiniu.com/nMvAvy",
  },
  {
    id: "aicoding",
    name: "AICoding",
    providerId: "aicoding",
    apiType: "openai-responses",
    baseUrl: "https://api.aicoding.inc",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://aicoding.inc",
  },
  {
    id: "subrouter",
    name: "SubRouter",
    providerId: "subrouter",
    apiType: "openai-responses",
    baseUrl: "https://subrouter.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://subrouter.ai",
  },
  {
    id: "apikey-fun",
    name: "APIKEY.FUN",
    providerId: "apikey-fun",
    apiType: "openai-responses",
    baseUrl: "https://api.apikey.fun/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://apikey.fun",
  },
  {
    id: "code0",
    name: "Code0",
    providerId: "code0",
    apiType: "openai-responses",
    baseUrl: "https://code0.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://code0.ai",
  },
  {
    id: "teamorouter",
    name: "TeamoRouter",
    providerId: "teamorouter",
    apiType: "openai-responses",
    baseUrl: "https://api.teamorouter.com/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://teamorouter.com",
  },
  {
    id: "claudecn",
    name: "ClaudeCN",
    providerId: "claudecn",
    apiType: "openai-responses",
    baseUrl: "https://claudecn.top/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://claudecn.top",
  },
  {
    id: "火山agentplan",
    name: "火山Agentplan",
    providerId: "火山agentplan",
    apiType: "openai-responses",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",
    models: [{ id: "ark-code-latest", name: "ark-code-latest" }],
    notes: "来自 CC Switch（cn_official）· https://www.volcengine.com/activity/codingplan?ac=MMAP8JTTCAQ2&rc=6J6FV5N2&utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
  },
  {
    id: "byteplus",
    name: "BytePlus",
    providerId: "byteplus",
    apiType: "openai-responses",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding/v3",
    models: [{ id: "ark-code-latest", name: "ark-code-latest" }],
    notes: "来自 CC Switch（cn_official）· https://www.byteplus.com/en/product/modelark?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
  },
  {
    id: "doubaoseed",
    name: "DouBaoSeed",
    providerId: "doubaoseed",
    apiType: "openai-responses",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    models: [{ id: "doubao-seed-2-1-pro-260628", name: "doubao-seed-2-1-pro-260628" }],
    notes: "来自 CC Switch（cn_official）· https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey?apikey=%7B%7D&utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    providerId: "siliconflow",
    apiType: "openai-responses",
    baseUrl: "https://api.siliconflow.cn/v1",
    models: [{ id: "Pro/MiniMaxAI/MiniMax-M2.7", name: "Pro/MiniMaxAI/MiniMax-M2.7" }],
    notes: "来自 CC Switch（aggregator）· https://siliconflow.cn",
  },
  {
    id: "siliconflow-en",
    name: "SiliconFlow en",
    providerId: "siliconflow-en",
    apiType: "openai-responses",
    baseUrl: "https://api.siliconflow.com/v1",
    models: [{ id: "MiniMaxAI/MiniMax-M2.7", name: "MiniMaxAI/MiniMax-M2.7" }],
    notes: "来自 CC Switch（aggregator）· https://siliconflow.com",
  },
  {
    id: "a6api",
    name: "A6API",
    providerId: "a6api",
    apiType: "openai-responses",
    baseUrl: "https://api.a6api.com/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://www.a6api.com",
  },
  {
    id: "atlascloud",
    name: "AtlasCloud",
    providerId: "atlascloud",
    apiType: "openai-responses",
    baseUrl: "https://api.atlascloud.ai/v1",
    models: [{ id: "zai-org/glm-5.1", name: "zai-org/glm-5.1" }],
    notes: "来自 CC Switch（aggregator）· https://www.atlascloud.ai/console/coding-plan",
  },
  {
    id: "compshare",
    name: "Compshare",
    providerId: "compshare",
    apiType: "openai-responses",
    baseUrl: "https://api.modelverse.cn/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://www.compshare.cn",
  },
  {
    id: "compshare-coding-plan",
    name: "Compshare Coding Plan",
    providerId: "compshare-coding-plan",
    apiType: "openai-responses",
    baseUrl: "https://cp.compshare.cn/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://www.compshare.cn",
  },
  {
    id: "ccsub",
    name: "CCSub",
    providerId: "ccsub",
    apiType: "openai-responses",
    baseUrl: "https://www.ccsub.net/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://www.ccsub.net",
  },
  {
    id: "sssaicode",
    name: "SSSAiCode",
    providerId: "sssaicode",
    apiType: "openai-responses",
    baseUrl: "https://node-hk.sssaicodeapi.com/api/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://sssaicodeapi.com",
  },
  {
    id: "micu",
    name: "Micu",
    providerId: "micu",
    apiType: "openai-responses",
    baseUrl: "https://www.micuapi.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://www.micuapi.ai",
  },
  {
    id: "rightcode",
    name: "RightCode",
    providerId: "rightcode",
    apiType: "openai-responses",
    baseUrl: "https://www.rightapi.ai/codex/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://www.rightapi.ai",
  },
  {
    id: "etok-ai",
    name: "ETok.ai",
    providerId: "etok-ai",
    apiType: "openai-responses",
    baseUrl: "https://api.etok.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://etok.ai",
  },
  {
    id: "cubence",
    name: "Cubence",
    providerId: "cubence",
    apiType: "openai-responses",
    baseUrl: "https://api.cubence.com/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://cubence.com",
  },
  {
    id: "crazyrouter",
    name: "CrazyRouter",
    providerId: "crazyrouter",
    apiType: "openai-responses",
    baseUrl: "https://cn.crazyrouter.com/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://www.crazyrouter.com",
  },
  {
    id: "dmxapi",
    name: "DMXAPI",
    providerId: "dmxapi",
    apiType: "openai-responses",
    baseUrl: "https://www.dmxapi.cn/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://www.dmxapi.cn",
  },
  {
    id: "sudocode-chat",
    name: "SudoCode.chat",
    providerId: "sudocode-chat",
    apiType: "openai-responses",
    baseUrl: "https://api.sudocode.chat/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://sudocode.chat",
  },
  {
    id: "sudocode-us",
    name: "SudoCode.us",
    providerId: "sudocode-us",
    apiType: "openai-responses",
    baseUrl: "https://sudocode.us/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://sudocode.us",
  },
  {
    id: "amux",
    name: "Amux",
    providerId: "amux",
    apiType: "openai-responses",
    baseUrl: "https://api.amux.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://amux.ai",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    providerId: "deepseek",
    apiType: "openai-responses",
    baseUrl: "https://api.deepseek.com",
    models: [{ id: "deepseek-v4-flash", name: "deepseek-v4-flash" }, { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", contextWindow: 1048576 }],
    notes: "来自 CC Switch（cn_official）· https://platform.deepseek.com",
  },
  {
    id: "zhipu-glm",
    name: "Zhipu GLM",
    providerId: "zhipu-glm",
    apiType: "openai-responses",
    baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    models: [{ id: "glm-5.2", name: "glm-5.2" }],
    notes: "来自 CC Switch（cn_official）· https://open.bigmodel.cn",
  },
  {
    id: "zhipu-glm-en",
    name: "Zhipu GLM en",
    providerId: "zhipu-glm-en",
    apiType: "openai-responses",
    baseUrl: "https://api.z.ai/api/coding/paas/v4",
    models: [{ id: "glm-5.2", name: "glm-5.2" }],
    notes: "来自 CC Switch（cn_official）· https://z.ai",
  },
  {
    id: "baidu-qianfan-coding-plan",
    name: "Baidu Qianfan Coding Plan",
    providerId: "baidu-qianfan-coding-plan",
    apiType: "openai-responses",
    baseUrl: "https://qianfan.baidubce.com/v2/coding",
    models: [{ id: "qianfan-code-latest", name: "qianfan-code-latest" }],
    notes: "来自 CC Switch（cn_official）· https://cloud.baidu.com/product/qianfan_modelbuilder",
  },
  {
    id: "bailian",
    name: "Bailian",
    providerId: "bailian",
    apiType: "openai-responses",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    models: [{ id: "qwen3-coder-plus", name: "qwen3-coder-plus" }],
    notes: "来自 CC Switch（cn_official）· https://bailian.console.aliyun.com",
  },
  {
    id: "tencent-hunyuan",
    name: "Tencent Hunyuan",
    providerId: "tencent-hunyuan",
    apiType: "openai-responses",
    baseUrl: "https://tokenhub.tencentmaas.com/v1",
    models: [{ id: "hy3", name: "hy3" }, { id: "hy3-preview", name: "Hy3 Preview", contextWindow: 256000 }],
    notes: "来自 CC Switch（cn_official）· https://cloud.tencent.com/product/tokenhub",
  },
  {
    id: "stepfun",
    name: "StepFun",
    providerId: "stepfun",
    apiType: "openai-responses",
    baseUrl: "https://api.stepfun.com/step_plan/v1",
    models: [{ id: "step-3.7-flash", name: "step-3.7-flash" }, { id: "step-3.5-flash-2603", name: "Step 3.5 Flash 2603", contextWindow: 262144 }, { id: "step-3.5-flash", name: "Step 3.5 Flash", contextWindow: 262144 }],
    notes: "来自 CC Switch（cn_official）· https://platform.stepfun.com/step-plan",
  },
  {
    id: "stepfun-en",
    name: "StepFun en",
    providerId: "stepfun-en",
    apiType: "openai-responses",
    baseUrl: "https://api.stepfun.ai/step_plan/v1",
    models: [{ id: "step-3.7-flash", name: "step-3.7-flash" }, { id: "step-3.5-flash-2603", name: "Step 3.5 Flash 2603", contextWindow: 262144 }, { id: "step-3.5-flash", name: "Step 3.5 Flash", contextWindow: 262144 }],
    notes: "来自 CC Switch（cn_official）· https://platform.stepfun.ai/step-plan",
  },
  {
    id: "modelscope",
    name: "ModelScope",
    providerId: "modelscope",
    apiType: "openai-responses",
    baseUrl: "https://api-inference.modelscope.cn/v1",
    models: [{ id: "ZhipuAI/GLM-5.1", name: "ZhipuAI/GLM-5.1" }],
    notes: "来自 CC Switch（aggregator）· https://modelscope.cn",
  },
  {
    id: "longcat",
    name: "Longcat",
    providerId: "longcat",
    apiType: "openai-responses",
    baseUrl: "https://api.longcat.chat/openai/v1",
    models: [{ id: "LongCat-2.0", name: "LongCat-2.0" }],
    notes: "来自 CC Switch（cn_official）· https://longcat.chat/platform",
  },
  {
    id: "minimax",
    name: "MiniMax",
    providerId: "minimax",
    apiType: "openai-responses",
    baseUrl: "https://api.minimaxi.com/v1",
    models: [{ id: "MiniMax-M3", name: "MiniMax-M3" }],
    notes: "来自 CC Switch（cn_official）· https://platform.minimaxi.com",
  },
  {
    id: "minimax-en",
    name: "MiniMax en",
    providerId: "minimax-en",
    apiType: "openai-responses",
    baseUrl: "https://api.minimax.io/v1",
    models: [{ id: "MiniMax-M3", name: "MiniMax-M3" }],
    notes: "来自 CC Switch（cn_official）· https://platform.minimax.io",
  },
  {
    id: "bailing",
    name: "BaiLing",
    providerId: "bailing",
    apiType: "openai-responses",
    baseUrl: "https://api.tbox.cn/api/llm/v1",
    models: [{ id: "Ling-2.6-1T", name: "Ling-2.6-1T" }],
    notes: "来自 CC Switch（cn_official）· https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
  },
  {
    id: "xiaomi-mimo",
    name: "Xiaomi MiMo",
    providerId: "xiaomi-mimo",
    apiType: "openai-responses",
    baseUrl: "https://api.xiaomimimo.com/v1",
    models: [{ id: "mimo-v2.5-pro", name: "mimo-v2.5-pro" }, { id: "mimo-v2.5", name: "MiMo V2.5", contextWindow: 1048576 }],
    notes: "来自 CC Switch（cn_official）· https://platform.xiaomimimo.com",
  },
  {
    id: "xiaomi-mimo-token-plan-china",
    name: "Xiaomi MiMo Token Plan (China)",
    providerId: "xiaomi-mimo-token-plan-china",
    apiType: "openai-responses",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
    models: [{ id: "mimo-v2.5-pro", name: "mimo-v2.5-pro" }, { id: "mimo-v2.5", name: "MiMo V2.5", contextWindow: 1048576 }],
    notes: "来自 CC Switch（cn_official）· https://platform.xiaomimimo.com/#/token-plan",
  },
  {
    id: "novita-ai",
    name: "Novita AI",
    providerId: "novita-ai",
    apiType: "openai-responses",
    baseUrl: "https://api.novita.ai/openai/v1",
    models: [{ id: "zai-org/glm-5.1", name: "zai-org/glm-5.1" }],
    notes: "来自 CC Switch（aggregator）· https://novita.ai",
  },
  {
    id: "xai-grok",
    name: "xAI (Grok)",
    providerId: "xai-grok",
    apiType: "openai-responses",
    baseUrl: "https://api.x.ai/v1",
    models: [{ id: "grok-4.5", name: "grok-4.5" }],
    notes: "来自 CC Switch（third_party）· https://x.ai/api",
  },
  {
    id: "nvidia",
    name: "Nvidia",
    providerId: "nvidia",
    apiType: "openai-responses",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    models: [{ id: "moonshotai/kimi-k2.5", name: "moonshotai/kimi-k2.5" }],
    notes: "来自 CC Switch（aggregator）· https://build.nvidia.com",
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    providerId: "opencode-go",
    apiType: "openai-responses",
    baseUrl: "https://opencode.ai/zen/go/v1",
    models: [{ id: "glm-5.2", name: "glm-5.2" }, { id: "glm-5.1", name: "GLM 5.1", contextWindow: 204800 }, { id: "kimi-k2.7-code", name: "Kimi K2.7 Code", contextWindow: 262144 }, { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" }, { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" }, { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro", contextWindow: 1048576 }],
    notes: "来自 CC Switch（third_party）· https://opencode.ai/go",
  },
  {
    id: "aihubmix",
    name: "AiHubMix",
    providerId: "aihubmix",
    apiType: "openai-responses",
    baseUrl: "https://aihubmix.com/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://aihubmix.com",
  },
  {
    id: "cherryin",
    name: "CherryIN",
    providerId: "cherryin",
    apiType: "openai-responses",
    baseUrl: "https://open.cherryin.net/v1",
    models: [{ id: "openai/gpt-5.6-sol", name: "openai/gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://open.cherryin.ai",
  },
  {
    id: "relaxycode",
    name: "RelaxyCode",
    providerId: "relaxycode",
    apiType: "openai-responses",
    baseUrl: "https://www.relaxycode.com/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://www.relaxycode.com",
  },
  {
    id: "e-flowcode",
    name: "E-FlowCode",
    providerId: "e-flowcode",
    apiType: "openai-responses",
    baseUrl: "https://e-flowcode.cc/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（third_party）· https://e-flowcode.cc",
  },
  {
    id: "pipellm",
    name: "PIPELLM",
    providerId: "pipellm",
    apiType: "openai-responses",
    baseUrl: "https://cc-api.pipellm.ai/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://code.pipellm.ai",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    providerId: "openrouter",
    apiType: "openai-responses",
    baseUrl: "https://openrouter.ai/api/v1",
    models: [{ id: "gpt-5.6-sol", name: "gpt-5.6-sol" }],
    notes: "来自 CC Switch（aggregator）· https://openrouter.ai",
  },
  {
    id: "therouter",
    name: "TheRouter",
    providerId: "therouter",
    apiType: "openai-responses",
    baseUrl: "https://api.therouter.ai/v1",
    models: [{ id: "openai/gpt-5.3-codex", name: "openai/gpt-5.3-codex" }],
    notes: "来自 CC Switch（aggregator）· https://therouter.ai",
  },
];

export function findProviderPreset(id: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find((preset) => preset.id === id);
}
